name: Kernel Build

on:
  workflow_dispatch:
    description: Automatic Build Kernel
    inputs:
      device_name:
        description: "device: r9s,o1s,t2s,p3s"
        required: true
        default: "r9s"
      clang_name:
        description: "clang: aosp or neutron"
        required: true
        default: "aosp"

jobs:
  build:
    runs-on: ubuntu-26.04
   
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: ${{ github.event.inputs.device_name }}
            clang: ${{ github.event.inputs.clang_name }}
            variant: ksu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Update apt
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          build-essential openjdk-8-jdk maven cmake byacc flex automake libtool-bin \
          bison binutils-dev libiberty-dev zip unzip libncurses5-dev curl git ninja-build \
          python3 libssl-dev gcc-aarch64-linux-gnu cpio gawk libarchive-tools lz4 repo

    - name: Set build flags for variant
      id: vars
      run: |
        if [ "${{ matrix.variant }}" = "ksu" ]; then
          echo "FLAGS=-k y" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.variant }}" = "resuki" ]; then
          echo "FLAGS=-r y" >> $GITHUB_OUTPUT
        else
          echo "FLAGS=" >> $GITHUB_OUTPUT
        fi

    - name: Run kernel build
      run: |
        chmod +x ./build.sh
        ./build.sh -m ${{ github.event.inputs.device_name }} -c ${{ github.event.inputs.clang_name }} ${{ steps.vars.outputs.FLAGS }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.device_name }}-${{ github.event.inputs.clang_name }}-${{ matrix.variant }}
        path: build/out/${{ github.event.inputs.device_name }}/*.zip
